package com.poultry.broiler.presentation.theme

import androidx.compose.ui.graphics.Color

// Forest Teal Light Palette
val ForestTealLightPrimary = Color(0xFF2E7D32)
val ForestTealLightOnPrimary = Color(0xFFFFFFFF)
val ForestTealLightPrimaryContainer = Color(0xFFB3F0B7)
val ForestTealLightOnPrimaryContainer = Color(0xFF002109)
val ForestTealLightSecondary = Color(0xFF526350)
val ForestTealLightOnSecondary = Color(0xFFFFFFFF)
val ForestTealLightSecondaryContainer = Color(0xFFD5E8D0)
val ForestTealLightOnSecondaryContainer = Color(0xFF101F10)
val ForestTealLightTertiary = Color(0xFF39656B)
val ForestTealLightOnTertiary = Color(0xFFFFFFFF)
val ForestTealLightTertiaryContainer = Color(0xFFBCEBF2)
val ForestTealLightOnTertiaryContainer = Color(0xFF002023)
val ForestTealLightError = Color(0xFFBA1A1A)
val ForestTealLightOnError = Color(0xFFFFFFFF)
val ForestTealLightErrorContainer = Color(0xFFFFDAD6)
val ForestTealLightOnErrorContainer = Color(0xFF410002)
val ForestTealLightBackground = Color(0xFFFDF9EC)
val ForestTealLightOnBackground = Color(0xFF1A1C19)
val ForestTealLightSurface = Color(0xFFFDF9EC)
val ForestTealLightOnSurface = Color(0xFF1A1C19)
val ForestTealLightSurfaceVariant = Color(0xFFDEE5D8)
val ForestTealLightOnSurfaceVariant = Color(0xFF424940)
val ForestTealLightOutline = Color(0xFF72796F)
val ForestTealLightOutlineVariant = Color(0xFFC2C9BD)
val ForestTealLightInverseSurface = Color(0xFF2F312D)
val ForestTealLightInverseOnSurface = Color(0xFFF1F1E5)
val ForestTealLightInversePrimary = Color(0xFF97D49C)
val ForestTealLightSurfaceTint = Color(0xFF2E7D32)

// Sleek Carbon Dark Palette
val SleekCarbonDarkPrimary = Color(0xFF97D49C)
val SleekCarbonDarkOnPrimary = Color(0xFF00390D)
val SleekCarbonDarkPrimaryContainer = Color(0xFF1B5E22)
val SleekCarbonDarkOnPrimaryContainer = Color(0xFFB3F0B7)
val SleekCarbonDarkSecondary = Color(0xFFB9CCB5)
val SleekCarbonDarkOnSecondary = Color(0xFF253424)
val SleekCarbonDarkSecondaryContainer = Color(0xFF3B4B39)
val SleekCarbonDarkOnSecondaryContainer = Color(0xFFD5E8D0)
val SleekCarbonDarkTertiary = Color(0xFFA1CED6)
val SleekCarbonDarkOnTertiary = Color(0xFF00363B)
val SleekCarbonDarkTertiaryContainer = Color(0xFF1F4D52)
val SleekCarbonDarkOnTertiaryContainer = Color(0xFFBCEBF2)
val SleekCarbonDarkError = Color(0xFFFFB4AB)
val SleekCarbonDarkOnError = Color(0xFF690005)
val SleekCarbonDarkErrorContainer = Color(0xFF93000A)
val SleekCarbonDarkOnErrorContainer = Color(0xFFFFDAD6)
val SleekCarbonDarkBackground = Color(0xFF121412)
val SleekCarbonDarkOnBackground = Color(0xFFE2E3DD)
val SleekCarbonDarkSurface = Color(0xFF121412)
val SleekCarbonDarkOnSurface = Color(0xFFE2E3DD)
val SleekCarbonDarkSurfaceVariant = Color(0xFF424940)
val SleekCarbonDarkOnSurfaceVariant = Color(0xFFC2C9BD)
val SleekCarbonDarkOutline = Color(0xFF8C9387)
val SleekCarbonDarkOutlineVariant = Color(0xFF424940)
val SleekCarbonDarkInverseSurface = Color(0xFFE2E3DD)
val SleekCarbonDarkInverseOnSurface = Color(0xFF2F312D)
val SleekCarbonDarkInversePrimary = Color(0xFF2E7D32)
val SleekCarbonDarkSurfaceTint = Color(0xFF97D49C)
