package com.poultry.broiler.presentation.theme

import androidx.compose.ui.graphics.Color

// Light Mode (Field Glare Reduction)
val ForestTealLightPrimary = Color(0xFF00685C)
val ForestTealLightOnPrimary = Color(0xFFFFFFFF)
val ForestTealLightPrimaryContainer = Color(0xFF1E8275)
val ForestTealLightOnPrimaryContainer = Color(0xFFF2FFFB)
val ForestTealLightSecondary = Color(0xFF865300)
val ForestTealLightOnSecondary = Color(0xFFFFFFFF)
val ForestTealLightSecondaryContainer = Color(0xFFFCAE49)
val ForestTealLightOnSecondaryContainer = Color(0xFF6E4300)
val ForestTealLightTertiary = Color(0xFF006A35)
val ForestTealLightOnTertiary = Color(0xFFFFFFFF)
val ForestTealLightTertiaryContainer = Color(0xFF008645)
val ForestTealLightOnTertiaryContainer = Color(0xFFF4FFF2)
val ForestTealLightError = Color(0xFFBA1A1A)
val ForestTealLightOnError = Color(0xFFFFFFFF)
val ForestTealLightErrorContainer = Color(0xFFFFDAD6)
val ForestTealLightOnErrorContainer = Color(0xFF93000A)
val ForestTealLightBackground = Color(0xFFF7F9FF)
val ForestTealLightOnBackground = Color(0xFF131D24)
val ForestTealLightSurface = Color(0xFFF7F9FF)
val ForestTealLightOnSurface = Color(0xFF131D24)
val ForestTealLightSurfaceVariant = Color(0xFFDAE3EE)
val ForestTealLightOnSurfaceVariant = Color(0xFF3E4946)
val ForestTealLightOutline = Color(0xFF6E7976)
val ForestTealLightOutlineVariant = Color(0xFFBDC9C5)
val ForestTealLightInverseSurface = Color(0xFF28313a)
val ForestTealLightInverseOnSurface = Color(0xFFe8f2fd)
val ForestTealLightInversePrimary = Color(0xFF7dd6c7)
val ForestTealLightSurfaceTint = Color(0xFF006b5f)
val ForestTealLightSuccess = Color(0xFF229954)
val ForestTealLightWarning = Color(0xFFD4AC0D)
val ForestTealLightDanger = Color(0xFFCB4335)

// Dark Mode (Sleek Carbon)
val SleekCarbonDarkPrimary = Color(0xFF2ECC71)
val SleekCarbonDarkOnPrimary = Color(0xFF0E141B)
val SleekCarbonDarkPrimaryContainer = Color(0xFF1B5E22)
val SleekCarbonDarkOnPrimaryContainer = Color(0xFFB3F0B7)
val SleekCarbonDarkSecondary = Color(0xFFF39C12)
val SleekCarbonDarkOnSecondary = Color(0xFFFFFFFF)
val SleekCarbonDarkSecondaryContainer = Color(0xFF3B4B39)
val SleekCarbonDarkOnSecondaryContainer = Color(0xFFD5E8D0)
val SleekCarbonDarkTertiary = Color(0xFFA1CED6)
val SleekCarbonDarkOnTertiary = Color(0xFF00363B)
val SleekCarbonDarkTertiaryContainer = Color(0xFF1F4D52)
val SleekCarbonDarkOnTertiaryContainer = Color(0xFFBCEBF2)
val SleekCarbonDarkError = Color(0xFFFFB4AB)
val SleekCarbonDarkOnError = Color(0xFF690005)
val SleekCarbonDarkErrorContainer = Color(0xFF93000A)
val SleekCarbonDarkOnErrorContainer = Color(0xFFFFDAD6)
val SleekCarbonDarkBackground = Color(0xFF0C1013)
val SleekCarbonDarkOnBackground = Color(0xFFEDEFF1)
val SleekCarbonDarkSurface = Color(0xFF171F26)
val SleekCarbonDarkOnSurface = Color(0xFFEDEFF1)
val SleekCarbonDarkSurfaceVariant = Color(0xFF242F3A)
val SleekCarbonDarkOnSurfaceVariant = Color(0xFFEDEFF1)
val SleekCarbonDarkOutline = Color(0xFF6E7976)
val SleekCarbonDarkOutlineVariant = Color(0xFFBDC9C5)
val SleekCarbonDarkInverseSurface = Color(0xFFEDEFF1)
val SleekCarbonDarkInverseOnSurface = Color(0xFF171F26)
val SleekCarbonDarkInversePrimary = Color(0xFF00685C)
val SleekCarbonDarkSurfaceTint = Color(0xFF2ECC71)
val SleekCarbonDarkSuccess = Color(0xFF27AE60)
val SleekCarbonDarkWarning = Color(0xFFF1C40F)
val SleekCarbonDarkDanger = Color(0xFFE74C3C)
